version: "3"

services:

  Test_Container: 
    
    build:
      context: ./YOLO
      dockerfile: Dockerfile
    image: "yolov8_engine:ver1.0"

    container_name: Test_Container
    volumes:
      - /mnt:/Drive
      - ./AICCTV:/code
      - ./ultralytics:/usr/src/ultralytics/ultralytics
    environment:
      - TZ=Asia/Seoul
    restart: always
    command: ["/opt/conda/bin/python", "/code/loop.py"]
    ipc: host  # IPC 모드를 호스트로 설정
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all  # 모든 GPU를 사용
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"