version: "3"

services:

  SETTING: 

    # 첫번째 컨테이너에서만 이미지를 빌드한다
    #############################
    build:
      context: ./YOLO
      dockerfile: Dockerfile
    image: "yolov8_engine:ver1.0"
    #############################
    container_name: SETTING
    volumes:
      - /mnt:/Drive
      - ./AICCTV:/code
      - ./ultralytics:/usr/src/ultralytics/ultralytics
    restart: always
    command: ["/opt/conda/bin/python", "/code/loop.py"]
    ipc: host  # IPC 모드를 호스트로 설정
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all  # 모든 GPU를 사용
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"

########################################################################################################
  BUGUN_Dong_1: 
    image: "yolov8_engine:ver1.0"
    container_name: BUGUN_Dong_1
    volumes:
      - /mnt:/Drive
      - ./AICCTV:/code
      - ./ultralytics:/usr/src/ultralytics/ultralytics
    environment:
      - TZ=Asia/Seoul
    restart: always
    command: ["/opt/conda/bin/python", "/code/Counter.py","--farm=BUGUN", "--house=Dong_1" ,"--counter=Polygon", "--video_path=/Drive/DATACENTER_SSD/AICCTV_VIDEO" ,"--counter_txt_path=/Drive/DATACENTER_SSD/AICCTV_LOG", "--detect_txt_path=/Drive/DATACENTER_SSD/AICCTV_Detect_Log"]
    ipc: host  # IPC 모드를 호스트로 설정
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all  # 모든 GPU를 사용
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
########################################################################################################

########################################################################################################
  BUGUN_Dong_2:
    image: "yolov8_engine:ver1.0"
    container_name: BUGUN_Dong_2
    volumes:
      - /mnt:/Drive
      - ./AICCTV:/code
      - ./ultralytics:/usr/src/ultralytics/ultralytics
    environment:
      - TZ=Asia/Seoul
    restart: always
    command: ["/opt/conda/bin/python", "/code/Counter.py","--farm=BUGUN", "--house=Dong_2" ,"--counter=Polygon", "--video_path=/Drive/DATACENTER_SSD/AICCTV_VIDEO" ,"--counter_txt_path=/Drive/DATACENTER_SSD/AICCTV_LOG", "--detect_txt_path=/Drive/DATACENTER_SSD/AICCTV_Detect_Log"]
    ipc: host  # IPC 모드를 호스트로 설정
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all  # 모든 GPU를 사용

    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
########################################################################################################

########################################################################################################
  BUGUN_Dong_3_FRONT:
    image: "yolov8_engine:ver1.0"
    container_name: BUGUN_Dong_3_FRONT
    volumes:
      - /mnt:/Drive
      - ./AICCTV:/code
      - ./ultralytics:/usr/src/ultralytics/ultralytics
    environment:
      - TZ=Asia/Seoul
    restart: always
    command: ["/opt/conda/bin/python", "/code/Counter.py","--farm=BUGUN", "--house=Dong_3_FRONT" ,"--counter=Polygon", "--video_path=/Drive/DATACENTER_SSD/AICCTV_VIDEO" ,"--counter_txt_path=/Drive/DATACENTER_SSD/AICCTV_LOG", "--detect_txt_path=/Drive/DATACENTER_SSD/AICCTV_Detect_Log"]
    ipc: host  # IPC 모드를 호스트로 설정
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all  # 모든 GPU를 사용

    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
########################################################################################################

########################################################################################################
  BUGUN_Dong_3_BACK:
    image: "yolov8_engine:ver1.0"
    container_name: BUGUN_Dong_3_BACK
    volumes:
      - /mnt:/Drive
      - ./AICCTV:/code
      - ./ultralytics:/usr/src/ultralytics/ultralytics
    environment:
      - TZ=Asia/Seoul
    restart: always
    command: ["/opt/conda/bin/python", "/code/Counter.py","--farm=BUGUN", "--house=Dong_3_BACK" ,"--counter=Polygon", "--video_path=/Drive/DATACENTER_SSD/AICCTV_VIDEO" ,"--counter_txt_path=/Drive/DATACENTER_SSD/AICCTV_LOG", "--detect_txt_path=/Drive/DATACENTER_SSD/AICCTV_Detect_Log"]
    ipc: host  # IPC 모드를 호스트로 설정
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all  # 모든 GPU를 사용

    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
########################################################################################################

########################################################################################################
  BUGUN_Dong_4:
    image: "yolov8_engine:ver1.0"
    container_name: BUGUN_Dong_4
    volumes:
      - /mnt:/Drive
      - ./AICCTV:/code
      - ./ultralytics:/usr/src/ultralytics/ultralytics
    environment:
      - TZ=Asia/Seoul
    restart: always
    command: ["/opt/conda/bin/python", "/code/Counter.py","--farm=BUGUN", "--house=Dong_4" ,"--counter=Polygon", "--video_path=/Drive/DATACENTER_SSD/AICCTV_VIDEO" ,"--counter_txt_path=/Drive/DATACENTER_SSD/AICCTV_LOG", "--detect_txt_path=/Drive/DATACENTER_SSD/AICCTV_Detect_Log"]
    ipc: host  # IPC 모드를 호스트로 설정
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all  # 모든 GPU를 사용

    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
########################################################################################################