version: "3"

services:

  BUGUN_Dong_1_DEAD: 

    # 첫번째 컨테이너에서만 이미지를 빌드한다
    #############################
    build:
      context: ./YOLO
      dockerfile: Dockerfile
    image: "yolov8_engine:ver1.0"
    #############################
    container_name: BUGUN_Dong_1_DEAD
    volumes:
      - /mnt:/Drive
      - ./AICCTV:/code
      - ./ultralytics:/usr/src/ultralytics/ultralytics
    restart: always
    command: ["/opt/conda/bin/python", "/code/Counter_BUGUN_Dong_1_DEAD.py"]
    ipc: host  # IPC 모드를 호스트로 설정
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all  # 모든 GPU를 사용