version: "3"
services:
    build:
      context: ./YOLO
      dockerfile: Dockerfile
    image: YOLOv8:ver1.0
    container_name: BUGUN_Dong_1_DEAD
    volumes:
      - /mnt:/Drive
      - ./AICCTV:/code
      - ./ultralytics:/usr/src/ultralytics
    command: ["/opt/conda/bin/python", "/code/Counter.py"]